# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnlaceRn.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EnlaceRn.proto',
  package='enlacern',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x45nlaceRn.proto\x12\x08\x65nlacern\"3\n\x0eusuarioRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\x0fusuarioResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"0\n\rEnlaceRequest\x12\x0e\n\x06\x65nlace\x18\x01 \x01(\t\x12\x0f\n\x07usuario\x18\x02 \x01(\t\"m\n\x0e\x45nlaceResponse\x12\x10\n\x08\x65nlaceId\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x03 \x01(\t\x12\x10\n\x08\x61\x63ortado\x18\x04 \x01(\t\x12\r\n\x05veces\x18\x05 \x01(\x05\x12\x0c\n\x04\x66oto\x18\x06 \x01(\t\"\x16\n\x06\x65nlace\x12\x0c\n\x04user\x18\x01 \x01(\t\"6\n\x0bListaEnlace\x12\'\n\x05\x65lace\x18\x01 \x03(\x0b\x32\x18.enlacern.EnlaceResponse\"#\n\x0f\x63lientesRequest\x12\x10\n\x08idEnlace\x18\x01 \x01(\x05\"H\n\x07\x63liente\x12\r\n\x05\x66\x65\x63ha\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x11\n\tnavegador\x18\x03 \x01(\t\x12\x0f\n\x07sistema\x18\x04 \x01(\t\"5\n\x0e\x63lienteReponse\x12#\n\x08\x63lientes\x18\x01 \x03(\x0b\x32\x11.enlacern.cliente2\xd5\x02\n\x08\x45nlaceRn\x12\x46\n\x0f\x61utentificacion\x12\x18.enlacern.usuarioRequest\x1a\x19.enlacern.usuarioResponse\x12\x44\n\x0fregistrarEnlace\x12\x17.enlacern.EnlaceRequest\x1a\x18.enlacern.EnlaceResponse\x12@\n\tgetEnlace\x12\x19.enlacern.clientesRequest\x1a\x18.enlacern.EnlaceResponse\x12\x35\n\ngetEnlaces\x12\x10.enlacern.enlace\x1a\x15.enlacern.ListaEnlace\x12\x42\n\x0bgetClientes\x12\x19.enlacern.clientesRequest\x1a\x18.enlacern.clienteReponseb\x06proto3'
)




_USUARIOREQUEST = _descriptor.Descriptor(
  name='usuarioRequest',
  full_name='enlacern.usuarioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='enlacern.usuarioRequest.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='enlacern.usuarioRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=79,
)


_USUARIORESPONSE = _descriptor.Descriptor(
  name='usuarioResponse',
  full_name='enlacern.usuarioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='enlacern.usuarioResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=110,
)


_ENLACEREQUEST = _descriptor.Descriptor(
  name='EnlaceRequest',
  full_name='enlacern.EnlaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enlace', full_name='enlacern.EnlaceRequest.enlace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usuario', full_name='enlacern.EnlaceRequest.usuario', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=160,
)


_ENLACERESPONSE = _descriptor.Descriptor(
  name='EnlaceResponse',
  full_name='enlacern.EnlaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enlaceId', full_name='enlacern.EnlaceResponse.enlaceId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='enlacern.EnlaceResponse.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fecha', full_name='enlacern.EnlaceResponse.fecha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acortado', full_name='enlacern.EnlaceResponse.acortado', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='veces', full_name='enlacern.EnlaceResponse.veces', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='foto', full_name='enlacern.EnlaceResponse.foto', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=271,
)


_ENLACE = _descriptor.Descriptor(
  name='enlace',
  full_name='enlacern.enlace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='enlacern.enlace.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=295,
)


_LISTAENLACE = _descriptor.Descriptor(
  name='ListaEnlace',
  full_name='enlacern.ListaEnlace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elace', full_name='enlacern.ListaEnlace.elace', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=351,
)


_CLIENTESREQUEST = _descriptor.Descriptor(
  name='clientesRequest',
  full_name='enlacern.clientesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idEnlace', full_name='enlacern.clientesRequest.idEnlace', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=388,
)


_CLIENTE = _descriptor.Descriptor(
  name='cliente',
  full_name='enlacern.cliente',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fecha', full_name='enlacern.cliente.fecha', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='enlacern.cliente.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='navegador', full_name='enlacern.cliente.navegador', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sistema', full_name='enlacern.cliente.sistema', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=462,
)


_CLIENTEREPONSE = _descriptor.Descriptor(
  name='clienteReponse',
  full_name='enlacern.clienteReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientes', full_name='enlacern.clienteReponse.clientes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=517,
)

_LISTAENLACE.fields_by_name['elace'].message_type = _ENLACERESPONSE
_CLIENTEREPONSE.fields_by_name['clientes'].message_type = _CLIENTE
DESCRIPTOR.message_types_by_name['usuarioRequest'] = _USUARIOREQUEST
DESCRIPTOR.message_types_by_name['usuarioResponse'] = _USUARIORESPONSE
DESCRIPTOR.message_types_by_name['EnlaceRequest'] = _ENLACEREQUEST
DESCRIPTOR.message_types_by_name['EnlaceResponse'] = _ENLACERESPONSE
DESCRIPTOR.message_types_by_name['enlace'] = _ENLACE
DESCRIPTOR.message_types_by_name['ListaEnlace'] = _LISTAENLACE
DESCRIPTOR.message_types_by_name['clientesRequest'] = _CLIENTESREQUEST
DESCRIPTOR.message_types_by_name['cliente'] = _CLIENTE
DESCRIPTOR.message_types_by_name['clienteReponse'] = _CLIENTEREPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

usuarioRequest = _reflection.GeneratedProtocolMessageType('usuarioRequest', (_message.Message,), {
  'DESCRIPTOR' : _USUARIOREQUEST,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.usuarioRequest)
  })
_sym_db.RegisterMessage(usuarioRequest)

usuarioResponse = _reflection.GeneratedProtocolMessageType('usuarioResponse', (_message.Message,), {
  'DESCRIPTOR' : _USUARIORESPONSE,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.usuarioResponse)
  })
_sym_db.RegisterMessage(usuarioResponse)

EnlaceRequest = _reflection.GeneratedProtocolMessageType('EnlaceRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENLACEREQUEST,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.EnlaceRequest)
  })
_sym_db.RegisterMessage(EnlaceRequest)

EnlaceResponse = _reflection.GeneratedProtocolMessageType('EnlaceResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENLACERESPONSE,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.EnlaceResponse)
  })
_sym_db.RegisterMessage(EnlaceResponse)

enlace = _reflection.GeneratedProtocolMessageType('enlace', (_message.Message,), {
  'DESCRIPTOR' : _ENLACE,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.enlace)
  })
_sym_db.RegisterMessage(enlace)

ListaEnlace = _reflection.GeneratedProtocolMessageType('ListaEnlace', (_message.Message,), {
  'DESCRIPTOR' : _LISTAENLACE,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.ListaEnlace)
  })
_sym_db.RegisterMessage(ListaEnlace)

clientesRequest = _reflection.GeneratedProtocolMessageType('clientesRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTESREQUEST,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.clientesRequest)
  })
_sym_db.RegisterMessage(clientesRequest)

cliente = _reflection.GeneratedProtocolMessageType('cliente', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTE,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.cliente)
  })
_sym_db.RegisterMessage(cliente)

clienteReponse = _reflection.GeneratedProtocolMessageType('clienteReponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTEREPONSE,
  '__module__' : 'EnlaceRn_pb2'
  # @@protoc_insertion_point(class_scope:enlacern.clienteReponse)
  })
_sym_db.RegisterMessage(clienteReponse)



_ENLACERN = _descriptor.ServiceDescriptor(
  name='EnlaceRn',
  full_name='enlacern.EnlaceRn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=520,
  serialized_end=861,
  methods=[
  _descriptor.MethodDescriptor(
    name='autentificacion',
    full_name='enlacern.EnlaceRn.autentificacion',
    index=0,
    containing_service=None,
    input_type=_USUARIOREQUEST,
    output_type=_USUARIORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='registrarEnlace',
    full_name='enlacern.EnlaceRn.registrarEnlace',
    index=1,
    containing_service=None,
    input_type=_ENLACEREQUEST,
    output_type=_ENLACERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getEnlace',
    full_name='enlacern.EnlaceRn.getEnlace',
    index=2,
    containing_service=None,
    input_type=_CLIENTESREQUEST,
    output_type=_ENLACERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getEnlaces',
    full_name='enlacern.EnlaceRn.getEnlaces',
    index=3,
    containing_service=None,
    input_type=_ENLACE,
    output_type=_LISTAENLACE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getClientes',
    full_name='enlacern.EnlaceRn.getClientes',
    index=4,
    containing_service=None,
    input_type=_CLIENTESREQUEST,
    output_type=_CLIENTEREPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENLACERN)

DESCRIPTOR.services_by_name['EnlaceRn'] = _ENLACERN

# @@protoc_insertion_point(module_scope)
